2017-02-11T14:49:16.208Z - error: uncaughtException: connection timeout date=Sat Feb 11 2017 09:49:16 GMT-0500 (EST), pid=32495, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=128974848, heapTotal=27299840, heapUsed=20654176, loadavg=[0.162109375, 0.08740234375, 0.08544921875], uptime=568490, trace=[column=17, file=/home/yun/workspace/shortUrl/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js, function=, line=169, method=null, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Db.emit, line=191, method=emit, native=false, column=14, file=/home/yun/workspace/shortUrl/node_modules/mongodb/lib/db.js, function=Server.listener, line=1798, method=listener, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Server.emit, line=188, method=emit, native=false, column=14, file=/home/yun/workspace/shortUrl/node_modules/mongodb/lib/server.js, function=, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Server.emit, line=188, method=emit, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js, function=, line=335, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js, function=, line=270, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false], stack=[Error: connection timeout,     at Db.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17),     at emitTwo (events.js:106:13),     at Db.emit (events.js:191:7),     at Server.listener (/home/yun/workspace/shortUrl/node_modules/mongodb/lib/db.js:1798:14),     at emitOne (events.js:96:13),     at Server.emit (events.js:188:7),     at Server.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb/lib/server.js:274:14),     at emitOne (events.js:96:13),     at Server.emit (events.js:188:7),     at Pool.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js:335:12),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js:270:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7)]
2017-09-11T15:13:20.184Z - error: uncaughtException: failed to connect to server [ds145669.mlab.com:45669] on first connect date=Mon Sep 11 2017 11:13:20 GMT-0400 (EDT), pid=2601, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=129843200, heapTotal=24154112, heapUsed=19071616, loadavg=[0.396484375, 0.494140625, 0.2451171875], uptime=273, trace=[column=35, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js, function=, line=326, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js, function=, line=270, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js, function=, line=175, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=connectErrorNT, line=1022, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [ds145669.mlab.com:45669] on first connect,     at Pool.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js:326:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js:270:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js:175:49),     at Socket.g (events.js:291:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at connectErrorNT (net.js:1022:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
2017-09-11T19:15:56.665Z - error: uncaughtException: data is not defined date=Mon Sep 11 2017 15:15:56 GMT-0400 (EDT), pid=2601, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=130043904, heapTotal=25202688, heapUsed=18799008, loadavg=[0.57861328125, 0.52099609375, 0.291015625], uptime=429, trace=[column=28, file=/home/yun/workspace/shortUrl/services/urlService.js, function=Command.callback, line=29, method=callback, native=false, column=21, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=normal_reply, line=721, method=null, native=false, column=9, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=RedisClient.return_reply, line=819, method=return_reply, native=false, column=18, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=JavascriptRedisParser.returnReply, line=192, method=returnReply, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js, function=JavascriptRedisParser.execute, line=560, method=execute, native=false, column=27, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=Readable.push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[ReferenceError: data is not defined,     at Command.callback (/home/yun/workspace/shortUrl/services/urlService.js:29:28),     at normal_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:721:21),     at RedisClient.return_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:819:9),     at JavascriptRedisParser.returnReply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:192:18),     at JavascriptRedisParser.execute (/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js:560:12),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/redis/index.js:274:27),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-09-11T19:15:58.009Z - error: uncaughtException: data is not defined date=Mon Sep 11 2017 15:15:58 GMT-0400 (EDT), pid=2601, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=130584576, heapTotal=25202688, heapUsed=19216376, loadavg=[0.5322265625, 0.51220703125, 0.2890625], uptime=430, trace=[column=28, file=/home/yun/workspace/shortUrl/services/urlService.js, function=Command.callback, line=29, method=callback, native=false, column=21, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=normal_reply, line=721, method=null, native=false, column=9, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=RedisClient.return_reply, line=819, method=return_reply, native=false, column=18, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=JavascriptRedisParser.returnReply, line=192, method=returnReply, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js, function=JavascriptRedisParser.execute, line=560, method=execute, native=false, column=27, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=Readable.push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[ReferenceError: data is not defined,     at Command.callback (/home/yun/workspace/shortUrl/services/urlService.js:29:28),     at normal_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:721:21),     at RedisClient.return_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:819:9),     at JavascriptRedisParser.returnReply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:192:18),     at JavascriptRedisParser.execute (/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js:560:12),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/redis/index.js:274:27),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-09-11T19:17:56.672Z - error: uncaughtException: data is not defined date=Mon Sep 11 2017 15:17:56 GMT-0400 (EDT), pid=2601, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=130564096, heapTotal=25202688, heapUsed=19199448, loadavg=[0.10888671875, 0.369140625, 0.259765625], uptime=549, trace=[column=28, file=/home/yun/workspace/shortUrl/services/urlService.js, function=Command.callback, line=29, method=callback, native=false, column=21, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=normal_reply, line=721, method=null, native=false, column=9, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=RedisClient.return_reply, line=819, method=return_reply, native=false, column=18, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=JavascriptRedisParser.returnReply, line=192, method=returnReply, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js, function=JavascriptRedisParser.execute, line=560, method=execute, native=false, column=27, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=Readable.push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[ReferenceError: data is not defined,     at Command.callback (/home/yun/workspace/shortUrl/services/urlService.js:29:28),     at normal_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:721:21),     at RedisClient.return_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:819:9),     at JavascriptRedisParser.returnReply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:192:18),     at JavascriptRedisParser.execute (/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js:560:12),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/redis/index.js:274:27),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-09-11T19:17:58.018Z - error: uncaughtException: data is not defined date=Mon Sep 11 2017 15:17:58 GMT-0400 (EDT), pid=2601, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=130834432, heapTotal=25202688, heapUsed=19584712, loadavg=[0.10009765625, 0.36279296875, 0.25830078125], uptime=550, trace=[column=28, file=/home/yun/workspace/shortUrl/services/urlService.js, function=Command.callback, line=29, method=callback, native=false, column=21, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=normal_reply, line=721, method=null, native=false, column=9, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=RedisClient.return_reply, line=819, method=return_reply, native=false, column=18, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=JavascriptRedisParser.returnReply, line=192, method=returnReply, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js, function=JavascriptRedisParser.execute, line=560, method=execute, native=false, column=27, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=Readable.push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[ReferenceError: data is not defined,     at Command.callback (/home/yun/workspace/shortUrl/services/urlService.js:29:28),     at normal_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:721:21),     at RedisClient.return_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:819:9),     at JavascriptRedisParser.returnReply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:192:18),     at JavascriptRedisParser.execute (/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js:560:12),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/redis/index.js:274:27),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-09-11T19:19:19.562Z - error: uncaughtException: Cannot find module 'express-useragent' date=Mon Sep 11 2017 15:19:19 GMT-0400 (EDT), pid=3408, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=140128256, heapTotal=38834176, heapUsed=19673824, loadavg=[0.20849609375, 0.32275390625, 0.25244140625], uptime=632, trace=[column=15, file=module.js, function=Module._resolveFilename, line=469, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=417, method=_load, native=false, column=17, file=module.js, function=Module.require, line=497, method=require, native=false, column=19, file=internal/module.js, function=require, line=20, method=null, native=false, column=17, file=/home/yun/workspace/shortUrl/server.js, function=null, line=8, method=null, native=false, column=32, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=579, method=.js, native=false, column=32, file=module.js, function=Module.load, line=487, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Module._load, line=438, method=_load, native=false, column=10, file=module.js, function=Module.runMain, line=604, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=394, method=null, native=false, column=9, file=bootstrap_node.js, function=startup, line=149, method=null, native=false, column=3, file=bootstrap_node.js, function=null, line=509, method=null, native=false], stack=[Error: Cannot find module 'express-useragent',     at Function.Module._resolveFilename (module.js:469:15),     at Function.Module._load (module.js:417:25),     at Module.require (module.js:497:17),     at require (internal/module.js:20:19),     at Object.<anonymous> (/home/yun/workspace/shortUrl/server.js:8:17),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.js:446:12),     at Function.Module._load (module.js:438:3),     at Module.runMain (module.js:604:10),     at run (bootstrap_node.js:394:7),     at startup (bootstrap_node.js:149:9),     at bootstrap_node.js:509:3]
2017-09-11T19:22:24.282Z - error: uncaughtException: data is not defined date=Mon Sep 11 2017 15:22:24 GMT-0400 (EDT), pid=3510, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=133181440, heapTotal=25202688, heapUsed=20225792, loadavg=[0.51904296875, 0.4140625, 0.296875], uptime=817, trace=[column=28, file=/home/yun/workspace/shortUrl/services/urlService.js, function=Command.callback, line=29, method=callback, native=false, column=21, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=normal_reply, line=726, method=null, native=false, column=9, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=RedisClient.return_reply, line=824, method=return_reply, native=false, column=18, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=JavascriptRedisParser.returnReply, line=192, method=returnReply, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js, function=JavascriptRedisParser.execute, line=574, method=execute, native=false, column=27, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=null, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[ReferenceError: data is not defined,     at Command.callback (/home/yun/workspace/shortUrl/services/urlService.js:29:28),     at normal_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:726:21),     at RedisClient.return_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:824:9),     at JavascriptRedisParser.returnReply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:192:18),     at JavascriptRedisParser.execute (/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js:574:12),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/redis/index.js:274:27),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-09-11T19:24:24.281Z - error: uncaughtException: data is not defined date=Mon Sep 11 2017 15:24:24 GMT-0400 (EDT), pid=3510, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=134782976, heapTotal=27299840, heapUsed=21694384, loadavg=[0.662109375, 0.4423828125, 0.3125], uptime=937, trace=[column=28, file=/home/yun/workspace/shortUrl/services/urlService.js, function=Command.callback, line=29, method=callback, native=false, column=21, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=normal_reply, line=726, method=null, native=false, column=9, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=RedisClient.return_reply, line=824, method=return_reply, native=false, column=18, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=JavascriptRedisParser.returnReply, line=192, method=returnReply, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js, function=JavascriptRedisParser.execute, line=574, method=execute, native=false, column=27, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=null, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[ReferenceError: data is not defined,     at Command.callback (/home/yun/workspace/shortUrl/services/urlService.js:29:28),     at normal_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:726:21),     at RedisClient.return_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:824:9),     at JavascriptRedisParser.returnReply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:192:18),     at JavascriptRedisParser.execute (/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js:574:12),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/redis/index.js:274:27),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-09-11T19:26:24.283Z - error: uncaughtException: data is not defined date=Mon Sep 11 2017 15:26:24 GMT-0400 (EDT), pid=3510, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=134660096, heapTotal=27299840, heapUsed=21554504, loadavg=[0.7578125, 0.66357421875, 0.41552734375], uptime=1057, trace=[column=28, file=/home/yun/workspace/shortUrl/services/urlService.js, function=Command.callback, line=29, method=callback, native=false, column=21, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=normal_reply, line=726, method=null, native=false, column=9, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=RedisClient.return_reply, line=824, method=return_reply, native=false, column=18, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=JavascriptRedisParser.returnReply, line=192, method=returnReply, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js, function=JavascriptRedisParser.execute, line=574, method=execute, native=false, column=27, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=null, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[ReferenceError: data is not defined,     at Command.callback (/home/yun/workspace/shortUrl/services/urlService.js:29:28),     at normal_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:726:21),     at RedisClient.return_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:824:9),     at JavascriptRedisParser.returnReply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:192:18),     at JavascriptRedisParser.execute (/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js:574:12),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/redis/index.js:274:27),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-09-11T19:35:35.843Z - error: uncaughtException: data is not defined date=Mon Sep 11 2017 15:35:35 GMT-0400 (EDT), pid=4107, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=133304320, heapTotal=28348416, heapUsed=20993288, loadavg=[0.4560546875, 0.4345703125, 0.37744140625], uptime=1608, trace=[column=28, file=/home/yun/workspace/shortUrl/services/urlService.js, function=Command.callback, line=29, method=callback, native=false, column=21, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=normal_reply, line=726, method=null, native=false, column=9, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=RedisClient.return_reply, line=824, method=return_reply, native=false, column=18, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=JavascriptRedisParser.returnReply, line=192, method=returnReply, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js, function=JavascriptRedisParser.execute, line=574, method=execute, native=false, column=27, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=null, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[ReferenceError: data is not defined,     at Command.callback (/home/yun/workspace/shortUrl/services/urlService.js:29:28),     at normal_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:726:21),     at RedisClient.return_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:824:9),     at JavascriptRedisParser.returnReply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:192:18),     at JavascriptRedisParser.execute (/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js:574:12),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/redis/index.js:274:27),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-09-11T19:37:46.746Z - error: uncaughtException: data is not defined date=Mon Sep 11 2017 15:37:46 GMT-0400 (EDT), pid=4107, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=134524928, heapTotal=28348416, heapUsed=21781768, loadavg=[0.94873046875, 0.64697265625, 0.46240234375], uptime=1739, trace=[column=28, file=/home/yun/workspace/shortUrl/services/urlService.js, function=Command.callback, line=29, method=callback, native=false, column=21, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=normal_reply, line=726, method=null, native=false, column=9, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=RedisClient.return_reply, line=824, method=return_reply, native=false, column=18, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=JavascriptRedisParser.returnReply, line=192, method=returnReply, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js, function=JavascriptRedisParser.execute, line=574, method=execute, native=false, column=27, file=/home/yun/workspace/shortUrl/node_modules/redis/index.js, function=null, line=274, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[ReferenceError: data is not defined,     at Command.callback (/home/yun/workspace/shortUrl/services/urlService.js:29:28),     at normal_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:726:21),     at RedisClient.return_reply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:824:9),     at JavascriptRedisParser.returnReply (/home/yun/workspace/shortUrl/node_modules/redis/index.js:192:18),     at JavascriptRedisParser.execute (/home/yun/workspace/shortUrl/node_modules/redis-parser/lib/parser.js:574:12),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/redis/index.js:274:27),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-09-11T20:52:26.868Z - error: uncaughtException: Ran out of retries trying to reconnect to "ds145669.mlab.com:45669". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher. date=Mon Sep 11 2017 16:52:26 GMT-0400 (EDT), pid=4107, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=143769600, heapTotal=29396992, heapUsed=24085856, loadavg=[0.48583984375, 1.20849609375, 1.2392578125], uptime=6219, trace=[column=11, file=/home/yun/workspace/shortUrl/node_modules/mongoose/lib/error/disconnected.js, function=MongooseError.DisconnectedError, line=22, method=DisconnectedError, native=false, column=31, file=/home/yun/workspace/shortUrl/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js, function=null, line=64, method=null, native=false, column=20, file=events.js, function=emitOne, line=101, method=null, native=false, column=7, file=events.js, function=Server.emit, line=188, method=emit, native=false, column=16, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=327, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=16, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=connectErrorNT, line=1022, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[DisconnectedError: Ran out of retries trying to reconnect to "ds145669.mlab.com:45669". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.,     at MongooseError.DisconnectedError (/home/yun/workspace/shortUrl/node_modules/mongoose/lib/error/disconnected.js:22:11),     at Server.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:64:31),     at emitOne (events.js:101:20),     at Server.emit (events.js:188:7),     at Pool.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js:327:16),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js:317:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js:187:49),     at Socket.g (events.js:291:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at connectErrorNT (net.js:1022:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
2017-09-12T02:05:58.772Z - error: uncaughtException: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out] date=Mon Sep 11 2017 22:05:58 GMT-0400 (EDT), pid=5691, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=130088960, heapTotal=25202688, heapUsed=18748248, loadavg=[1.56494140625, 1.43798828125, 0.892578125], uptime=557, trace=[column=35, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=336, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=197, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=339, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out],     at Pool.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js:336:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js:280:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js:197:10),     at Socket.g (events.js:291:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:339:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
2017-09-12T02:07:02.193Z - error: uncaughtException: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out] date=Mon Sep 11 2017 22:07:02 GMT-0400 (EDT), pid=6050, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=128667648, heapTotal=27299840, heapUsed=19803200, loadavg=[0.68798828125, 1.19970703125, 0.8466796875], uptime=620, trace=[column=35, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=336, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=197, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=339, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out],     at Pool.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js:336:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js:280:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js:197:10),     at Socket.g (events.js:291:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:339:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
2017-09-12T02:12:56.812Z - error: uncaughtException: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out] date=Mon Sep 11 2017 22:12:56 GMT-0400 (EDT), pid=6388, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=143081472, heapTotal=40931328, heapUsed=19220480, loadavg=[0.77001953125, 1.01611328125, 0.8935546875], uptime=975, trace=[column=35, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=336, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=197, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=339, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out],     at Pool.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js:336:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js:280:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js:197:10),     at Socket.g (events.js:291:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:339:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
2017-09-12T02:51:03.558Z - error: uncaughtException: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out] date=Mon Sep 11 2017 22:51:03 GMT-0400 (EDT), pid=7349, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=128405504, heapTotal=27299840, heapUsed=19860264, loadavg=[0.1796875, 0.21484375, 0.32958984375], uptime=3262, trace=[column=35, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=336, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=197, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=339, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out],     at Pool.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js:336:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js:280:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js:197:10),     at Socket.g (events.js:291:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:339:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
2017-09-12T02:52:38.698Z - error: uncaughtException: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out] date=Mon Sep 11 2017 22:52:38 GMT-0400 (EDT), pid=7413, uid=1000, gid=1000, cwd=/home/yun/workspace/shortUrl, execPath=/usr/bin/nodejs, version=v6.9.2, argv=[/usr/bin/nodejs, /home/yun/workspace/shortUrl/server.js], rss=130461696, heapTotal=26251264, heapUsed=21492552, loadavg=[0.2783203125, 0.2275390625, 0.32080078125], uptime=3357, trace=[column=35, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=336, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=197, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=339, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [ds145669.mlab.com:45669] on first connect [MongoError: connection 0 to ds145669.mlab.com:45669 timed out],     at Pool.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/topologies/server.js:336:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/pool.js:280:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (/home/yun/workspace/shortUrl/node_modules/mongodb-core/lib/connection/connection.js:197:10),     at Socket.g (events.js:291:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:339:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
